[package]
name = "web"
version = "0.1.0"
authors = ["stas"]

[dependencies]
iron = "0.6.*"
params = "0.8.*"
router = ">=0.5, <0.7"
hyper = "0.10"
mount = ">= 0.3, <0.5"
time = "0.1"
url = "1.1"
staticfile = "*"
rand = "0.6.5"
rustc-serialize = "0.3.24"
